### PR TITLE
Refactor 1

### PR DESCRIPTION
**Pull request by thisisibrahimd**
Implemented mono repo and added scoretrak-scoretrakapis repo contained buf generated output.

### CODE REVIEW

**Comment by thisisibrahimd** [comment]
Going to test ci with pre-release

**Comment by thisisibrahimd** [comment]
CI is as usual (https://github.com/ScoreTrak/client/actions/runs/2104081944) and inspecting the container with dive (https://gochronicles.com/dive/) show the same output as previous containers.

**Review by L1ghtman2k — APPROVED** [review]

**Comment by L1ghtman2k** [comment]
This is a lot of files to check haha, If it looked fine on ur end, let's merge this

**Comment by thisisibrahimd** [comment]
Yeah a lot of files, haha. Just moving them from one folder to another spams the files changed count :(.

**Pull request merged**
